### ISSUE TITLE
Crashes sometimes when system goes to standby

### ISSUE THREAD

**Issue by donmega** [JvGinkel/iconomi-mac-statusbar#1]
Hi,

I am loving this piece of software, it's exactly what i have been searching for! Thank you! When my system goes to standby, it sometimes crashes with this:

Get "https://api.iconomi.com/v1/user/balance?currency=EUR": dial tcp: lookup api.iconomi.com: no such hostpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x42f4e24]

goroutine 6 [running]:
main.iconomiBalance()
	/Users/wu/Documents/iconomi/main.go:131 +0x584
created by main.main
	/Users/wu/Documents/iconomi/main.go:170 +0x19c
exit status 2

**Comment by JvGinkel** [comment]
Thank you for reporting this, can you try again as I created a fix for this with commit b2849b7d7d9453a9a938bfd3cc509ae9c942c30f

**Comment by donmega** [comment]
Yes, seems to be working fine with the newest update. Thank you very much!!
